[package]
name = "reh"
version = "1.1.0"
edition = "2024"

[dependencies]
eframe = "0.28"
rfd = "0.14"
cpal = "0.15"
symphonia = { version = "0.5", features = ["all"] }
signalsmith-stretch = "0.1"
ringbuf = "0.3" # For thread-safe audio buffering

